### ISSUE TITLE
JSP + css

### ISSUE THREAD

**Issue by thomasso93** [thomasso93/AuctionService#1]
Adrian zajmij się proszę połączeniem Twojego szablonu z index.jsp tak, żeby cała strona główna działała jako servlet page. Jak to się uda to można pomyśleć nad stworzeniem kolejnych podstron jsp, ważne żeby miały one angielskie nazwy mówiące o tym co one robią.

**Comment by lodowkapotwor** [comment]
A cos dla mnie do roboty? Jest juz logowanie?

10 sty 2015 17:04 thomasso93 notifications@github.com napisał(a):
Closed #1.

---

Reply to this email directly or view it on GitHub:
https://github.com/thomasso93/AuctionService/issues/1#event-216974531
